version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17.5

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: List Directory Contents
          command: ls -la portal
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "portal/package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --prefix portal
      - save_cache:
          paths:
            - portal/node_modules
          key: v1-dependencies-{{ checksum "portal/package.json" }}

workflows:
  version: 2
  main_workflow:
    jobs:
      - install_dependencies

