version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:16  # Use a Node.js image suitable for your React app
    working_directory: ~/project

jobs:
  build:
    steps:
      - checkout
      
      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            npm install

      # Run tests (optional but recommended)
      - run:
          name: Run tests
          command: |
            npm test -- --watchAll=false

      # Build the React app
      - run:
          name: Build React app
          command: |
            npm run build

      # Run SonarScanner
      - run:
          name: Run SonarScanner
          command: |
            npx sonar-scanner -Dsonar.projectKey=Daud1024_APDS7311_POE \
            -Dsonar.organization=daud1024 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.nodejs.executable=$(which node) \
            -Dsonar.login=${SONAR_TOKEN}  # Note: This is kept for backward compatibility, but it is deprecated

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
