version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14.17.5

jobs:
  install_dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: List Directory Contents
          command: ls -la portal
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "portal/package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install --prefix portal
      - save_cache:
          paths:
            - portal/node_modules
          key: v1-dependencies-{{ checksum "portal/package.json" }}

  sonar_scan:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "portal/package.json" }}
      - run:
          name: Install SonarQube Scanner
          command: npm install --save-dev sonarqube-scanner --prefix portal
      - run:
          name: Run SonarQube Scan
          command: |
            npx sonarqube-scanner \
              -Dsonar.projectKey=Daud1024_APDS7311_POE \
              -Dsonar.organization=daud1024 \
              -Dsonar.sources=portal \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  main_workflow:
    jobs:
      - install_dependencies
      - sonar_scan
