version: 2.1

executors:
  default:
    docker:
      - image: circleci/python:3.8 
    working_directory: ~/project

jobs:
  build:
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run SonarScanner
          command: |
            npx sonar-scanner -Dsonar.projectKey=Daud1024_APDS7311_POE \
            -Dsonar.organization=daud1024 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.nodejs.executable=$(which node) \
            -Dsonar.login=${SONAR_TOKEN} # This line is kept for backward compatibility, but note it's deprecated

workflows:
  version: 2
  build_and_scan:
    jobs:
      - build
