version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14
    working_directory: ~/project

jobs:
  sonar_scan:
    docker:
      - image: circleci/openjdk:11.0.11
    environment:
      # Set SONAR_USER_HOME to a location in the working directory
      SONAR_USER_HOME: "${HOME}/.sonar"
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner.zip -d $HOME
            export PATH="$HOME/sonar-scanner-4.6.2.2472-linux/bin:$PATH"
      - run:
          name: Run SonarQube Scanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=Daud1024_APDS7311_POE \
              -Dsonar.organization=daud1024 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
      - persist_to_workspace:
          root: ~/project
          paths:
            - .sonar

workflows:
  version: 2
  sonarcloud:
    jobs:
      - sonar_scan

