name: DevSecOps

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js 18 or later

      - name: Install dependencies
        run: |
          cd portal/server  # Change to the directory where package.json is located
          npm install

      - name: Run Tests
        run: |
          cd portal/server  # Ensure we are in the right directory
          chmod +x ./node_modules/.bin/jest  # Make jest executable
          npx jest tests.test.js
